Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from lifelines import KaplanMeierFitter
kmf = KaplanMeierFitter()
kmf.fit(T, event_observed = E)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/usr/local/lib/python3.8/site-packages/lifelines/utils/__init__.py[0m in [0;36mcheck_nans_or_infs[0;34m(df_or_array)[0m
[1;32m   1169[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1170[0;31m         [0minfs[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0misinf[0m[0;34m([0m[0mdf_or_array[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1171[0m     [0;32mexcept[0m [0mTypeError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

During handling of the above exception, another exception occurred:

[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/usr/local/lib/python3.8/site-packages/lifelines/utils/__init__.py[0m in [0;36mcheck_nans_or_infs[0;34m(df_or_array)[0m
[1;32m   1177[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1178[0;31m             [0minfs[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0misinf[0m[0;34m([0m[0mdf_or_array[0m[0;34m.[0m[0mastype[0m[0;34m([0m[0mfloat[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1179[0m         [0;32mexcept[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: could not convert string to float: "'--"

During handling of the above exception, another exception occurred:

[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-43-7f53473c2b25>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mfrom[0m [0mlifelines[0m [0;32mimport[0m [0mKaplanMeierFitter[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mkmf[0m [0;34m=[0m [0mKaplanMeierFitter[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mkmf[0m[0;34m.[0m[0mfit[0m[0;34m([0m[0mT[0m[0;34m,[0m [0mevent_observed[0m [0;34m=[0m [0mE[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/usr/local/lib/python3.8/site-packages/lifelines/utils/__init__.py[0m in [0;36mf[0;34m(model, *args, **kwargs)[0m
[1;32m     52[0m         [0;32mdef[0m [0mf[0m[0;34m([0m[0mmodel[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     53[0m             [0mcls[0m[0;34m.[0m[0mset_censoring_type[0m[0;34m([0m[0mmodel[0m[0;34m,[0m [0mcls[0m[0;34m.[0m[0mRIGHT[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 54[0;31m             [0;32mreturn[0m [0mfunction[0m[0;34m([0m[0mmodel[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     55[0m [0;34m[0m[0m
[1;32m     56[0m         [0;32mreturn[0m [0mf[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.8/site-packages/lifelines/fitters/kaplan_meier_fitter.py[0m in [0;36mfit[0;34m(self, durations, event_observed, timeline, entry, label, alpha, ci_labels, weights)[0m
[1;32m    112[0m         """
[1;32m    113[0m [0;34m[0m[0m
[0;32m--> 114[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_fit[0m[0;34m([0m[0mdurations[0m[0;34m,[0m [0mevent_observed[0m[0;34m,[0m [0mtimeline[0m[0;34m,[0m [0mentry[0m[0;34m,[0m [0mlabel[0m[0;34m,[0m [0malpha[0m[0;34m,[0m [0mci_labels[0m[0;34m,[0m [0mweights[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    115[0m [0;34m[0m[0m
[1;32m    116[0m     [0;34m@[0m[0mCensoringType[0m[0;34m.[0m[0minterval_censoring[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.8/site-packages/lifelines/fitters/kaplan_meier_fitter.py[0m in [0;36m_fit[0;34m(self, durations, event_observed, timeline, entry, label, alpha, ci_labels, weights)[0m
[1;32m    293[0m         """
[1;32m    294[0m         [0mdurations[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0masarray[0m[0;34m([0m[0mdurations[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 295[0;31m         [0mself[0m[0;34m.[0m[0m_check_values[0m[0;34m([0m[0mdurations[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    296[0m [0;34m[0m[0m
[1;32m    297[0m         [0;32mif[0m [0mevent_observed[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.8/site-packages/lifelines/fitters/kaplan_meier_fitter.py[0m in [0;36m_check_values[0;34m(self, array)[0m
[1;32m    365[0m [0;34m[0m[0m
[1;32m    366[0m     [0;32mdef[0m [0m_check_values[0m[0;34m([0m[0mself[0m[0;34m,[0m [0marray[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 367[0;31m         [0mcheck_nans_or_infs[0m[0;34m([0m[0marray[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    368[0m [0;34m[0m[0m
[1;32m    369[0m     [0;32mdef[0m [0mplot_loglogs[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.8/site-packages/lifelines/utils/__init__.py[0m in [0;36mcheck_nans_or_infs[0;34m(df_or_array)[0m
[1;32m   1178[0m             [0minfs[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0misinf[0m[0;34m([0m[0mdf_or_array[0m[0;34m.[0m[0mastype[0m[0;34m([0m[0mfloat[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1179[0m         [0;32mexcept[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1180[0;31m             [0;32mraise[0m [0mTypeError[0m[0;34m([0m[0;34m"Wrong dtype '%s'."[0m [0;34m%[0m [0mdf_or_array[0m[0;34m.[0m[0mdtype[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1181[0m [0;34m[0m[0m
[1;32m   1182[0m     [0;32mif[0m [0minfs[0m[0;34m.[0m[0many[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: Wrong dtype 'object'.
TypeError: Wrong dtype 'object'.

